export const productsData = {
  data: [
    {
      name: "Premia American Badam",
      price: 419,
      weight: 500,
      category: "dry fruits",
      url: "images/almonds.png",
    },
    {
      name: "Premia Kaju",
      price: 400,
      weight: 500,
      category: "dry fruits",
      url: "images/kaju.png",
    },
    {
      name: "Premia Pista Salty",
      price: 200,
      weight: 200,
      category: "dry fruits",
      url: "images/pista.png",
    },
    {
      name: "Rajma White",
      price: 100,
      weight: 500,
      category: "pulses",
      url: "images/rajma.png",
    },
    {
      name: "Nutrela Soya Mini Chunks",
      price: 50,
      weight: 200,
      category: "pulses",
      url: "images/soyachucks.png",
    },
    {
      name: "Desi Kabuli Chana",
      price: 138,
      weight: 1000,
      category: "pulses",
      url: "images/chana.png",
    },
    {
      name: "Urad Dal Premium",
      price: 80,
      weight: 500,
      category: "pulses",
      url: "images/uraddal.png",
    },
    {
      name: "Makai For Popcorn",
      price: 30,
      weight: 200,
      category: "grains",
      url: "images/popcorn.png",
    },
    {
      name: "Rice Atta",
      price: 18,
      weight: 500,
      category: "flour",
      url: "images/riceflour.png",
    },
    {
      name: "Organic Ragi Flour",
      price: 60,
      weight: 500,
      category: "flour",
      url: "images/ragiflour.png",
    },
    {
      name: "Bajari",
      price: 35,
      weight: 500,
      category: "grains",
      url: "images/bajri.png",
    },
    {
      name: "Premia Sabudana Small",
      price: 34,
      weight: 500,
      category: "grains",
      url: "images/sabudana.png",
    },
    {
      name: "Organic India Quinoa",
      price: 265,
      weight: 500,
      category: "grains",
      url: "images/quinoa.png",
    },
    {
      name: "Satyam Rava",
      price: 28,
      weight: 500,
      category: "flour",
      url: "images/rava.png",
    },
    {
      name: "Satyam Besan",
      price: 52,
      weight: 500,
      category: "flour",
      url: "images/besan.png",
    },
    {
      name: "Chowli Premium",
      price: 71,
      weight: 500,
      category: "pulses",
      url: "images/chowli.png",
    },
    {
      name: "Vatana Green",
      price: 91,
      weight: 500,
      category: "pulses",
      url: "images/vatana.png",
    },
  ],
};
